FROM eclipse-temurin:22-alpine
COPY . /home/jgp
WORKDIR /home/jgp
RUN ./gradlew clean -x test bootJar
RUN mv /home/jgp/build/libs/*.jar /home/jgp-1.0.0.jar && rm -rf /home/jgp
ENTRYPOINT ["java"]
CMD ["-jar", "/home/jgp-1.0.0.jar"]
EXPOSE 8082