DROP TABLE IF EXISTS bmo_data;

CREATE TABLE clients (
	id                BIGINT GENERATED ALWAYS AS IDENTITY     NOT NULL,
	date_created timestamp DEFAULT CURRENT_TIMESTAMP,
	last_modified timestamp NULL,
	business_name VARCHAR(255) NULL,
	jgp_id VARCHAR(255) NULL,
	phone_number VARCHAR(255) NULL,
	owner_gender VARCHAR(255) NULL,
	owner_age INT NULL,
	business_location VARCHAR(255) NULL,
	industry_sector VARCHAR(255) NULL,
	business_segment VARCHAR(255) NULL,
	is_business_registered BOOLEAN NULL,
	registration_number VARCHAR(255) NULL,
	has_bmo_membership BOOLEAN NULL,
	bmo_membership VARCHAR(255) NULL,
	best_monthly_revenue DECIMAL(19,4) NULL,
	worst_monthly_revenue VARCHAR(255) NULL,
    total_regular_employees INT NULL,
    youth_regular_employees INT NULL,
    total_casual_employees INT NULL,
    youth_casual_employees INT NULL,
    sample_records VARCHAR(255) NULL,
    ta_needs VARCHAR(255) NULL,
    person_with_disability VARCHAR(255) NULL,
    refugee_status VARCHAR(255) NULL,
    is_active BOOLEAN NULL,
	created_by_id BIGINT NULL,
	last_modified_by_id BIGINT NULL,
	CONSTRAINT client_pkey PRIMARY KEY (id),
	CONSTRAINT client_unique UNIQUE (jgp_id),
	CONSTRAINT M_USER_ON_MODIFIED_BY FOREIGN KEY (last_modified_by_id) REFERENCES users(id),
	CONSTRAINT M_USER_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users(id)
);

CREATE TABLE bmo_client_data (
	id                BIGINT GENERATED ALWAYS AS IDENTITY     NOT NULL,
	date_created timestamp DEFAULT CURRENT_TIMESTAMP,
	last_modified timestamp NULL,
	partner_id BIGINT NULL,
	client_id BIGINT NULL,
    form_submitted_on date NULL,
    is_applicant_eligible BOOLEAN NULL,
    tas_attended INT NULL,
    ta_sessions_attended INT NULL,
    recommended_for_finance BOOLEAN NULL,
    decision_date date NULL,
    fi_business_referred VARCHAR(255) NULL,
    date_partner_recorded date NULL,
    date_recorded_to_jgp date NULL,
	created_by_id BIGINT NULL,
	last_modified_by_id BIGINT NULL,
	CONSTRAINT bmo_pkey PRIMARY KEY (id),
	CONSTRAINT M_USER_ON_MODIFIED_BY FOREIGN KEY (last_modified_by_id) REFERENCES users(id),
	CONSTRAINT M_USER_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users(id),
	CONSTRAINT M_PARTNER_ON_BMO FOREIGN KEY (partner_id) REFERENCES partners(id),
	CONSTRAINT M_CLIENT_ON_BMO FOREIGN KEY (client_id) REFERENCES clients(id)
);

